2021-05-06 16:27:02,140 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:27:02,144 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:27:06,786 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:27:06,787 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:27:11,526 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:27:11,527 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:27:15,263 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:27:15,264 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:27:22,447 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:27:22,447 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:27:30,604 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:27:30,604 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:27:43,869 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:27:43,875 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:28:00,333 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:28:00,334 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:28:21,381 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:28:21,382 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:28:52,423 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:28:52,424 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:29:36,406 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:29:36,408 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:30:11,282 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:30:11,283 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:30:29,494 - INFO - root - Plugin 'Backup' added
2021-05-06 16:30:29,502 - INFO - root - Plugin 'Feedback' added
2021-05-06 16:30:29,514 - INFO - root - Plugin 'Shutdown' added
2021-05-06 16:30:29,518 - INFO - root - Plugin 'Repeat' added
2021-05-06 16:30:29,523 - INFO - root - Plugin 'Update' added
2021-05-06 16:30:29,533 - INFO - root - Plugin 'Logfile' added
2021-05-06 16:30:29,545 - INFO - root - Plugin 'Manual' added
2021-05-06 16:30:29,557 - INFO - root - Plugin 'Social' added
2021-05-06 16:30:29,560 - INFO - root - Plugin 'People' added
2021-05-06 16:30:29,562 - INFO - root - Plugin 'Value' added
2021-05-06 16:30:29,565 - INFO - root - Plugin 'Admin' added
2021-05-06 16:30:29,566 - INFO - root - Plugin 'Help' added
2021-05-06 16:30:29,568 - INFO - root - Plugin 'Description' added
2021-05-06 16:30:29,570 - INFO - root - Plugin 'Volume' added
2021-05-06 16:30:29,572 - INFO - root - Plugin 'Change' added
2021-05-06 16:30:29,574 - INFO - root - Plugin 'Market' added
2021-05-06 16:30:29,574 - INFO - root - Plugin 'Events' added
2021-05-06 16:30:29,577 - INFO - root - Plugin 'Start' added
2021-05-06 16:30:29,580 - INFO - root - Plugin 'Developer' added
2021-05-06 16:30:29,581 - INFO - root - Plugin 'Donate' added
2021-05-06 16:30:29,585 - INFO - root - Plugin 'Restart' added
2021-05-06 16:30:29,586 - INFO - root - Plugin 'Wallets' added
2021-05-06 16:30:29,588 - WARNING - root - File 'alert.py' can't be loaded as a plugin: module 'opencryptobot.plugins.alert' has no attribute 'Alert'
2021-05-06 16:30:29,588 - INFO - root - Plugin 'Exchanges' added
2021-05-06 16:30:29,590 - INFO - root - Plugin 'Search' added
2021-05-06 16:30:29,591 - INFO - root - Plugin 'Compare' added
2021-05-06 16:30:29,591 - INFO - root - Plugin 'About' added
2021-05-06 16:30:29,593 - INFO - root - Plugin 'Top' added
2021-05-06 16:30:29,600 - INFO - root - Plugin 'Ico' added
2021-05-06 16:30:29,601 - INFO - root - Plugin 'Bpmn' added
2021-05-06 16:30:29,602 - INFO - root - Plugin 'Marketcap' added
2021-05-06 16:30:29,604 - INFO - root - Plugin 'Alltimehigh' added
2021-05-06 16:30:29,606 - INFO - root - Plugin 'Pools' added
2021-05-06 16:30:29,607 - INFO - root - Plugin 'Worst' added
2021-05-06 16:30:29,610 - INFO - root - Plugin 'Fiftyone' added
2021-05-06 16:30:29,612 - INFO - root - Plugin 'News' added
2021-05-06 16:30:29,618 - INFO - root - Plugin 'Roi' added
2021-05-06 16:30:29,619 - INFO - root - Plugin 'Team' added
2021-05-06 16:30:29,619 - INFO - root - Plugin 'Stats' added
2021-05-06 16:30:29,619 - INFO - root - Plugin 'Decentralized' added
2021-05-06 16:30:29,621 - INFO - root - Plugin 'Best' added
2021-05-06 16:30:29,629 - INFO - root - Plugin 'Price' added
2021-05-06 16:30:29,630 - INFO - root - Plugin 'Info' added
2021-05-06 16:30:29,834 - INFO - root - Plugin 'Whitepaper' added
2021-05-06 16:30:30,017 - INFO - root - Plugin 'Twitter' added
2021-05-06 16:30:33,263 - INFO - root - Plugin 'Global' added
2021-05-06 16:30:33,265 - INFO - root - Plugin 'Chart' added
2021-05-06 16:30:33,280 - INFO - root - Plugin 'Trends' added
2021-05-06 16:30:33,414 - INFO - root - Plugin 'Candlestick' added
2021-05-06 16:30:33,417 - INFO - root - Starting Caching
2021-05-06 16:30:36,665 - ERROR - JobQueue - An uncaught error was raised while executing job refresh
Traceback (most recent call last):
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 23, in refresh
    APICache.refresh_coinmarketcap_coin_list()
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 39, in refresh_coinmarketcap_coin_list
    APICache.cmc_coin_list = Market().listings()["data"]
TypeError: 'JSONDecodeError' object is not subscriptable
2021-05-06 16:30:39,609 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:30:39,609 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:30:44,411 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:30:44,412 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:30:44,996 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:30:44,997 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:30:49,766 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:30:49,767 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:31:00,282 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:31:00,283 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:31:05,306 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:31:05,308 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:31:10,771 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:31:10,772 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:31:15,072 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:31:15,073 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:31:18,130 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:31:18,131 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:31:27,550 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:31:28,061 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:31:35,709 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:31:35,711 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:32:04,029 - INFO - root - Plugin 'Backup' added
2021-05-06 16:32:04,060 - INFO - root - Plugin 'Description' added
2021-05-06 16:32:04,061 - INFO - root - Plugin 'Change' added
2021-05-06 16:32:04,061 - INFO - root - Plugin 'Team' added
2021-05-06 16:32:04,072 - INFO - root - Plugin 'Feedback' added
2021-05-06 16:32:04,073 - INFO - root - Plugin 'Admin' added
2021-05-06 16:32:04,074 - INFO - root - Plugin 'Search' added
2021-05-06 16:32:04,076 - INFO - root - Plugin 'Events' added
2021-05-06 16:32:04,103 - INFO - root - Plugin 'Manual' added
2021-05-06 16:32:04,127 - INFO - root - Plugin 'Exchanges' added
2021-05-06 16:32:04,131 - INFO - root - Plugin 'Bpmn' added
2021-05-06 16:32:04,141 - INFO - root - Plugin 'Developer' added
2021-05-06 16:32:04,143 - INFO - root - Plugin 'Start' added
2021-05-06 16:32:04,153 - INFO - root - Plugin 'Pools' added
2021-05-06 16:32:04,157 - INFO - root - Plugin 'Worst' added
2021-05-06 16:32:04,160 - INFO - root - Plugin 'Best' added
2021-05-06 16:32:04,161 - INFO - root - Plugin 'Alltimehigh' added
2021-05-06 16:32:04,162 - INFO - root - Plugin 'Logfile' added
2021-05-06 16:32:04,162 - INFO - root - Plugin 'Top' added
2021-05-06 16:32:04,165 - INFO - root - Plugin 'Volume' added
2021-05-06 16:32:04,200 - INFO - root - Plugin 'About' added
2021-05-06 16:32:04,202 - WARNING - root - File 'alert.py' can't be loaded as a plugin: module 'opencryptobot.plugins.alert' has no attribute 'Alert'
2021-05-06 16:32:04,204 - INFO - root - Plugin 'Social' added
2021-05-06 16:32:04,207 - INFO - root - Plugin 'Stats' added
2021-05-06 16:32:04,207 - INFO - root - Plugin 'Value' added
2021-05-06 16:32:04,208 - INFO - root - Plugin 'Shutdown' added
2021-05-06 16:32:04,210 - INFO - root - Plugin 'People' added
2021-05-06 16:32:04,211 - INFO - root - Plugin 'Repeat' added
2021-05-06 16:32:04,213 - INFO - root - Plugin 'Wallets' added
2021-05-06 16:32:04,213 - INFO - root - Plugin 'Help' added
2021-05-06 16:32:04,213 - INFO - root - Plugin 'Compare' added
2021-05-06 16:32:04,214 - INFO - root - Plugin 'Marketcap' added
2021-05-06 16:32:04,226 - INFO - root - Plugin 'Donate' added
2021-05-06 16:32:04,227 - INFO - root - Plugin 'Market' added
2021-05-06 16:32:04,229 - INFO - root - Plugin 'Update' added
2021-05-06 16:32:04,230 - INFO - root - Plugin 'Info' added
2021-05-06 16:32:04,230 - INFO - root - Plugin 'Fiftyone' added
2021-05-06 16:32:04,231 - INFO - root - Plugin 'Ico' added
2021-05-06 16:32:04,232 - INFO - root - Plugin 'Roi' added
2021-05-06 16:32:04,232 - INFO - root - Plugin 'Decentralized' added
2021-05-06 16:32:04,233 - INFO - root - Plugin 'Restart' added
2021-05-06 16:32:04,239 - INFO - root - Plugin 'News' added
2021-05-06 16:32:04,248 - INFO - root - Plugin 'Price' added
2021-05-06 16:32:04,532 - INFO - root - Plugin 'Whitepaper' added
2021-05-06 16:32:04,814 - INFO - root - Plugin 'Twitter' added
2021-05-06 16:32:07,417 - INFO - root - Plugin 'Global' added
2021-05-06 16:32:07,418 - INFO - root - Plugin 'Chart' added
2021-05-06 16:32:07,428 - INFO - root - Plugin 'Trends' added
2021-05-06 16:32:07,551 - INFO - root - Plugin 'Candlestick' added
2021-05-06 16:32:07,554 - INFO - root - Starting Caching
2021-05-06 16:32:20,027 - ERROR - JobQueue - An uncaught error was raised while executing job refresh
Traceback (most recent call last):
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 23, in refresh
    APICache.refresh_coinmarketcap_coin_list()
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 39, in refresh_coinmarketcap_coin_list
    APICache.cmc_coin_list = Market().listings()["data"]
TypeError: 'JSONDecodeError' object is not subscriptable
2021-05-06 16:36:18,371 - INFO - root - Plugin 'Backup' added
2021-05-06 16:36:18,375 - INFO - root - Plugin 'Update' added
2021-05-06 16:36:18,390 - INFO - root - Plugin 'Shutdown' added
2021-05-06 16:36:18,392 - INFO - root - Plugin 'Feedback' added
2021-05-06 16:36:18,436 - INFO - root - Plugin 'Social' added
2021-05-06 16:36:18,440 - INFO - root - Plugin 'Description' added
2021-05-06 16:36:18,453 - INFO - root - Plugin 'Stats' added
2021-05-06 16:36:18,461 - INFO - root - Plugin 'Market' added
2021-05-06 16:36:18,462 - INFO - root - Plugin 'Restart' added
2021-05-06 16:36:18,465 - INFO - root - Plugin 'Top' added
2021-05-06 16:36:18,468 - INFO - root - Plugin 'Alltimehigh' added
2021-05-06 16:36:18,471 - INFO - root - Plugin 'Search' added
2021-05-06 16:36:18,475 - INFO - root - Plugin 'Volume' added
2021-05-06 16:36:18,489 - INFO - root - Plugin 'Events' added
2021-05-06 16:36:18,490 - INFO - root - Plugin 'Compare' added
2021-05-06 16:36:18,492 - INFO - root - Plugin 'Help' added
2021-05-06 16:36:18,493 - INFO - root - Plugin 'Ico' added
2021-05-06 16:36:18,493 - INFO - root - Plugin 'Logfile' added
2021-05-06 16:36:18,498 - INFO - root - Plugin 'Manual' added
2021-05-06 16:36:18,507 - INFO - root - Plugin 'Marketcap' added
2021-05-06 16:36:18,511 - INFO - root - Plugin 'Developer' added
2021-05-06 16:36:18,512 - INFO - root - Plugin 'Admin' added
2021-05-06 16:36:18,513 - INFO - root - Plugin 'Exchanges' added
2021-05-06 16:36:18,514 - INFO - root - Plugin 'Start' added
2021-05-06 16:36:18,514 - INFO - root - Plugin 'Value' added
2021-05-06 16:36:18,515 - INFO - root - Plugin 'Bpmn' added
2021-05-06 16:36:18,517 - INFO - root - Plugin 'About' added
2021-05-06 16:36:18,525 - INFO - root - Plugin 'Repeat' added
2021-05-06 16:36:18,528 - INFO - root - Plugin 'Worst' added
2021-05-06 16:36:18,530 - INFO - root - Plugin 'Team' added
2021-05-06 16:36:18,535 - INFO - root - Plugin 'Fiftyone' added
2021-05-06 16:36:18,536 - INFO - root - Plugin 'Wallets' added
2021-05-06 16:36:18,539 - INFO - root - Plugin 'Decentralized' added
2021-05-06 16:36:18,539 - INFO - root - Plugin 'People' added
2021-05-06 16:36:18,540 - INFO - root - Plugin 'Donate' added
2021-05-06 16:36:18,543 - INFO - root - Plugin 'Info' added
2021-05-06 16:36:18,545 - INFO - root - Plugin 'Roi' added
2021-05-06 16:36:18,546 - INFO - root - Plugin 'News' added
2021-05-06 16:36:18,547 - INFO - root - Plugin 'Best' added
2021-05-06 16:36:18,547 - INFO - root - Plugin 'Change' added
2021-05-06 16:36:18,548 - WARNING - root - File 'alert.py' can't be loaded as a plugin: module 'opencryptobot.plugins.alert' has no attribute 'Alert'
2021-05-06 16:36:18,548 - INFO - root - Plugin 'Pools' added
2021-05-06 16:36:18,559 - INFO - root - Plugin 'Price' added
2021-05-06 16:36:18,813 - INFO - root - Plugin 'Whitepaper' added
2021-05-06 16:36:19,011 - INFO - root - Plugin 'Twitter' added
2021-05-06 16:36:21,730 - INFO - root - Plugin 'Global' added
2021-05-06 16:36:21,731 - INFO - root - Plugin 'Chart' added
2021-05-06 16:36:21,740 - INFO - root - Plugin 'Trends' added
2021-05-06 16:36:21,864 - INFO - root - Plugin 'Candlestick' added
2021-05-06 16:36:21,867 - INFO - root - Starting Caching
2021-05-06 16:36:23,228 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:36:23,229 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:36:27,301 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:36:27,302 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:36:28,350 - ERROR - JobQueue - An uncaught error was raised while executing job refresh
Traceback (most recent call last):
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 23, in refresh
    APICache.refresh_coinmarketcap_coin_list()
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 39, in refresh_coinmarketcap_coin_list
    APICache.cmc_coin_list = Market().listings()["data"]
TypeError: 'JSONDecodeError' object is not subscriptable
2021-05-06 16:36:28,372 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:36:28,373 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:36:32,940 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:36:32,941 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:36:34,522 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:36:34,523 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:36:39,845 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:36:39,845 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:36:42,167 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:36:46,235 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:36:46,236 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:36:49,680 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:36:50,333 - ERROR - root - Timed out - {'update_id': 406256759, 'message': {'message_id': 227, 'date': 1620308200, 'chat': {'id': 1062954233, 'type': 'private', 'username': 'paemmisyon', 'first_name': 'Paemisyon'}, 'text': '/p btt', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 2}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1062954233, 'first_name': 'Paemisyon', 'is_bot': False, 'username': 'paemmisyon', 'language_code': 'en'}}}
2021-05-06 16:36:51,119 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:36:51,120 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:36:54,249 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:36:54,249 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:36:59,379 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:36:59,383 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:37:04,700 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:37:04,700 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:37:12,361 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:37:12,362 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:37:16,435 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:37:16,436 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:37:27,892 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:37:27,892 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:37:31,965 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:37:31,966 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:37:52,305 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:37:52,305 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:38:18,005 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:38:18,005 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:38:22,085 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:38:22,088 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:39:00,598 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:39:00,598 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:39:04,667 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:39:04,667 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:39:34,734 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:39:34,734 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:39:38,817 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:39:38,819 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:39:58,074 - INFO - root - Plugin 'Social' added
2021-05-06 16:39:58,086 - INFO - root - Plugin 'Feedback' added
2021-05-06 16:39:58,103 - INFO - root - Plugin 'Alltimehigh' added
2021-05-06 16:39:58,109 - INFO - root - Plugin 'Manual' added
2021-05-06 16:39:58,121 - INFO - root - Plugin 'Market' added
2021-05-06 16:39:58,125 - INFO - root - Plugin 'Events' added
2021-05-06 16:39:58,141 - INFO - root - Plugin 'Backup' added
2021-05-06 16:39:58,155 - INFO - root - Plugin 'Developer' added
2021-05-06 16:39:58,158 - INFO - root - Plugin 'Team' added
2021-05-06 16:39:58,171 - INFO - root - Plugin 'Compare' added
2021-05-06 16:39:58,171 - INFO - root - Plugin 'Help' added
2021-05-06 16:39:58,174 - INFO - root - Plugin 'Value' added
2021-05-06 16:39:58,175 - INFO - root - Plugin 'Update' added
2021-05-06 16:39:58,178 - INFO - root - Plugin 'Wallets' added
2021-05-06 16:39:58,182 - INFO - root - Plugin 'Repeat' added
2021-05-06 16:39:58,190 - INFO - root - Plugin 'Start' added
2021-05-06 16:39:58,225 - INFO - root - Plugin 'Change' added
2021-05-06 16:39:58,230 - INFO - root - Plugin 'Marketcap' added
2021-05-06 16:39:58,231 - INFO - root - Plugin 'Exchanges' added
2021-05-06 16:39:58,231 - INFO - root - Plugin 'Description' added
2021-05-06 16:39:58,233 - INFO - root - Plugin 'Bpmn' added
2021-05-06 16:39:58,236 - INFO - root - Plugin 'Restart' added
2021-05-06 16:39:58,240 - INFO - root - Plugin 'Worst' added
2021-05-06 16:39:58,242 - INFO - root - Plugin 'Ico' added
2021-05-06 16:39:58,250 - INFO - root - Plugin 'Shutdown' added
2021-05-06 16:39:58,252 - INFO - root - Plugin 'About' added
2021-05-06 16:39:58,252 - INFO - root - Plugin 'Info' added
2021-05-06 16:39:58,254 - INFO - root - Plugin 'Top' added
2021-05-06 16:39:58,260 - INFO - root - Plugin 'Roi' added
2021-05-06 16:39:58,264 - INFO - root - Plugin 'Admin' added
2021-05-06 16:39:58,265 - INFO - root - Plugin 'Donate' added
2021-05-06 16:39:58,266 - INFO - root - Plugin 'News' added
2021-05-06 16:39:58,272 - WARNING - root - File 'alert.py' can't be loaded as a plugin: module 'opencryptobot.plugins.alert' has no attribute 'Alert'
2021-05-06 16:39:58,272 - INFO - root - Plugin 'Volume' added
2021-05-06 16:39:58,273 - INFO - root - Plugin 'Pools' added
2021-05-06 16:39:58,274 - INFO - root - Plugin 'Search' added
2021-05-06 16:39:58,274 - INFO - root - Plugin 'Logfile' added
2021-05-06 16:39:58,277 - INFO - root - Plugin 'People' added
2021-05-06 16:39:58,282 - INFO - root - Plugin 'Fiftyone' added
2021-05-06 16:39:58,291 - INFO - root - Plugin 'Stats' added
2021-05-06 16:39:58,291 - INFO - root - Plugin 'Price' added
2021-05-06 16:39:58,295 - INFO - root - Plugin 'Best' added
2021-05-06 16:39:58,305 - INFO - root - Plugin 'Decentralized' added
2021-05-06 16:39:58,563 - INFO - root - Plugin 'Whitepaper' added
2021-05-06 16:39:58,702 - INFO - root - Plugin 'Twitter' added
2021-05-06 16:40:01,522 - INFO - root - Plugin 'Global' added
2021-05-06 16:40:01,524 - INFO - root - Plugin 'Chart' added
2021-05-06 16:40:01,531 - INFO - root - Plugin 'Trends' added
2021-05-06 16:40:01,689 - INFO - root - Plugin 'Candlestick' added
2021-05-06 16:40:01,695 - INFO - root - Starting Caching
2021-05-06 16:40:03,061 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:03,062 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:40:03,948 - ERROR - JobQueue - An uncaught error was raised while executing job refresh
Traceback (most recent call last):
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 23, in refresh
    APICache.refresh_coinmarketcap_coin_list()
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 39, in refresh_coinmarketcap_coin_list
    APICache.cmc_coin_list = Market().listings()["data"]
TypeError: 'JSONDecodeError' object is not subscriptable
2021-05-06 16:40:07,138 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:07,139 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:40:08,212 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:08,212 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:40:11,891 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:11,891 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:40:12,788 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:12,789 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:40:13,459 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:13,459 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:40:18,900 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:18,901 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:40:20,072 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:20,073 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:40:23,518 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:23,519 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:40:28,404 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:28,405 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:40:33,537 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:33,537 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:40:37,605 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:37,605 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:40:42,860 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:42,861 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:40:46,934 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:46,934 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:40:48,394 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:48,395 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:40:49,981 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:40:49,982 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:41:01,442 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:41:01,443 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:41:05,509 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:41:05,510 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:41:17,001 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:41:17,002 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:41:21,078 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:41:21,079 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:41:22,672 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 16:41:22,672 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 16:41:38,159 - INFO - root - Plugin 'Backup' added
2021-05-06 16:41:38,182 - INFO - root - Plugin 'Update' added
2021-05-06 16:41:38,215 - INFO - root - Plugin 'Manual' added
2021-05-06 16:41:38,222 - INFO - root - Plugin 'Start' added
2021-05-06 16:41:38,226 - INFO - root - Plugin 'Events' added
2021-05-06 16:41:38,227 - INFO - root - Plugin 'Top' added
2021-05-06 16:41:38,229 - INFO - root - Plugin 'Social' added
2021-05-06 16:41:38,240 - INFO - root - Plugin 'Market' added
2021-05-06 16:41:38,240 - INFO - root - Plugin 'Roi' added
2021-05-06 16:41:38,245 - INFO - root - Plugin 'Repeat' added
2021-05-06 16:41:38,248 - INFO - root - Plugin 'Shutdown' added
2021-05-06 16:41:38,248 - INFO - root - Plugin 'Compare' added
2021-05-06 16:41:38,257 - WARNING - root - File 'alert.py' can't be loaded as a plugin: module 'opencryptobot.plugins.alert' has no attribute 'Alert'
2021-05-06 16:41:38,257 - INFO - root - Plugin 'Alltimehigh' added
2021-05-06 16:41:38,257 - INFO - root - Plugin 'Stats' added
2021-05-06 16:41:38,258 - INFO - root - Plugin 'Developer' added
2021-05-06 16:41:38,261 - INFO - root - Plugin 'Restart' added
2021-05-06 16:41:38,278 - INFO - root - Plugin 'People' added
2021-05-06 16:41:38,283 - INFO - root - Plugin 'Fiftyone' added
2021-05-06 16:41:38,292 - INFO - root - Plugin 'Admin' added
2021-05-06 16:41:38,295 - INFO - root - Plugin 'Donate' added
2021-05-06 16:41:38,297 - INFO - root - Plugin 'Bpmn' added
2021-05-06 16:41:38,304 - INFO - root - Plugin 'About' added
2021-05-06 16:41:38,309 - INFO - root - Plugin 'Team' added
2021-05-06 16:41:38,310 - INFO - root - Plugin 'Logfile' added
2021-05-06 16:41:38,314 - INFO - root - Plugin 'Volume' added
2021-05-06 16:41:38,314 - INFO - root - Plugin 'Feedback' added
2021-05-06 16:41:38,317 - INFO - root - Plugin 'Best' added
2021-05-06 16:41:38,318 - INFO - root - Plugin 'Ico' added
2021-05-06 16:41:38,323 - INFO - root - Plugin 'Description' added
2021-05-06 16:41:38,323 - INFO - root - Plugin 'Wallets' added
2021-05-06 16:41:38,325 - INFO - root - Plugin 'Marketcap' added
2021-05-06 16:41:38,329 - INFO - root - Plugin 'Exchanges' added
2021-05-06 16:41:38,334 - INFO - root - Plugin 'Worst' added
2021-05-06 16:41:38,341 - INFO - root - Plugin 'Change' added
2021-05-06 16:41:38,341 - INFO - root - Plugin 'Value' added
2021-05-06 16:41:38,342 - INFO - root - Plugin 'Search' added
2021-05-06 16:41:38,347 - INFO - root - Plugin 'Info' added
2021-05-06 16:41:38,350 - INFO - root - Plugin 'News' added
2021-05-06 16:41:38,350 - INFO - root - Plugin 'Help' added
2021-05-06 16:41:38,353 - INFO - root - Plugin 'Decentralized' added
2021-05-06 16:41:38,356 - INFO - root - Plugin 'Price' added
2021-05-06 16:41:38,357 - INFO - root - Plugin 'Pools' added
2021-05-06 16:41:38,587 - INFO - root - Plugin 'Whitepaper' added
2021-05-06 16:41:38,709 - INFO - root - Plugin 'Twitter' added
2021-05-06 16:41:39,738 - INFO - root - Plugin 'Global' added
2021-05-06 16:41:39,739 - INFO - root - Plugin 'Chart' added
2021-05-06 16:41:39,742 - INFO - root - Plugin 'Trends' added
2021-05-06 16:41:39,785 - INFO - root - Plugin 'Candlestick' added
2021-05-06 16:41:39,787 - INFO - root - Starting Caching
2021-05-06 16:41:44,525 - ERROR - JobQueue - An uncaught error was raised while executing job refresh
Traceback (most recent call last):
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 23, in refresh
    APICache.refresh_coinmarketcap_coin_list()
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 39, in refresh_coinmarketcap_coin_list
    APICache.cmc_coin_list = Market().listings()["data"]
TypeError: 'JSONDecodeError' object is not subscriptable
2021-05-06 16:55:18,883 - ERROR - root - Timed out - {'update_id': 406256764, 'message': {'message_id': 239, 'date': 1620309043, 'chat': {'id': 1062954233, 'type': 'private', 'username': 'paemmisyon', 'first_name': 'Paemisyon'}, 'text': '/help', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 5}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1062954233, 'first_name': 'Paemisyon', 'is_bot': False, 'username': 'paemmisyon', 'language_code': 'tr'}}}
2021-05-06 17:08:48,460 - INFO - root - Plugin 'Feedback' added
2021-05-06 17:08:48,460 - INFO - root - Plugin 'Update' added
2021-05-06 17:08:48,461 - INFO - root - Plugin 'Backup' added
2021-05-06 17:08:48,471 - INFO - root - Plugin 'Alltimehigh' added
2021-05-06 17:08:48,486 - INFO - root - Plugin 'Manual' added
2021-05-06 17:08:48,486 - INFO - root - Plugin 'Start' added
2021-05-06 17:08:48,488 - INFO - root - Plugin 'Stats' added
2021-05-06 17:08:48,490 - INFO - root - Plugin 'Roi' added
2021-05-06 17:08:48,521 - INFO - root - Plugin 'Logfile' added
2021-05-06 17:08:48,522 - INFO - root - Plugin 'About' added
2021-05-06 17:08:48,524 - INFO - root - Plugin 'Top' added
2021-05-06 17:08:48,538 - INFO - root - Plugin 'Volume' added
2021-05-06 17:08:48,539 - INFO - root - Plugin 'Shutdown' added
2021-05-06 17:08:48,552 - INFO - root - Plugin 'Market' added
2021-05-06 17:08:48,558 - INFO - root - Plugin 'People' added
2021-05-06 17:08:48,562 - INFO - root - Plugin 'Fiftyone' added
2021-05-06 17:08:48,563 - INFO - root - Plugin 'Events' added
2021-05-06 17:08:48,567 - INFO - root - Plugin 'Description' added
2021-05-06 17:08:48,568 - INFO - root - Plugin 'Value' added
2021-05-06 17:08:48,571 - INFO - root - Plugin 'Compare' added
2021-05-06 17:08:48,582 - INFO - root - Plugin 'Ico' added
2021-05-06 17:08:48,585 - INFO - root - Plugin 'Bpmn' added
2021-05-06 17:08:48,587 - INFO - root - Plugin 'Marketcap' added
2021-05-06 17:08:48,587 - INFO - root - Plugin 'Worst' added
2021-05-06 17:08:48,588 - INFO - root - Plugin 'Search' added
2021-05-06 17:08:48,591 - INFO - root - Plugin 'Restart' added
2021-05-06 17:08:48,593 - INFO - root - Plugin 'Team' added
2021-05-06 17:08:48,593 - INFO - root - Plugin 'Social' added
2021-05-06 17:08:48,597 - INFO - root - Plugin 'Help' added
2021-05-06 17:08:48,604 - INFO - root - Plugin 'Donate' added
2021-05-06 17:08:48,605 - INFO - root - Plugin 'News' added
2021-05-06 17:08:48,605 - INFO - root - Plugin 'Change' added
2021-05-06 17:08:48,607 - INFO - root - Plugin 'Price' added
2021-05-06 17:08:48,609 - WARNING - root - File 'alert.py' can't be loaded as a plugin: module 'opencryptobot.plugins.alert' has no attribute 'Alert'
2021-05-06 17:08:48,607 - INFO - root - Plugin 'Developer' added
2021-05-06 17:08:48,612 - INFO - root - Plugin 'Exchanges' added
2021-05-06 17:08:48,619 - INFO - root - Plugin 'Repeat' added
2021-05-06 17:08:48,620 - INFO - root - Plugin 'Info' added
2021-05-06 17:08:48,624 - INFO - root - Plugin 'Admin' added
2021-05-06 17:08:48,624 - INFO - root - Plugin 'Decentralized' added
2021-05-06 17:08:48,629 - INFO - root - Plugin 'Pools' added
2021-05-06 17:08:48,629 - INFO - root - Plugin 'Best' added
2021-05-06 17:08:48,631 - INFO - root - Plugin 'Wallets' added
2021-05-06 17:08:48,867 - INFO - root - Plugin 'Whitepaper' added
2021-05-06 17:08:49,062 - INFO - root - Plugin 'Twitter' added
2021-05-06 17:08:51,678 - INFO - root - Plugin 'Global' added
2021-05-06 17:08:51,680 - INFO - root - Plugin 'Chart' added
2021-05-06 17:08:51,690 - INFO - root - Plugin 'Trends' added
2021-05-06 17:08:51,822 - INFO - root - Plugin 'Candlestick' added
2021-05-06 17:08:51,826 - INFO - root - Starting Caching
2021-05-06 17:08:53,188 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:08:53,188 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:08:57,265 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:08:57,266 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:08:58,348 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:08:58,350 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:09:02,919 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:09:02,920 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:09:03,011 - ERROR - JobQueue - An uncaught error was raised while executing job refresh
Traceback (most recent call last):
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 23, in refresh
    APICache.refresh_coinmarketcap_coin_list()
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 39, in refresh_coinmarketcap_coin_list
    APICache.cmc_coin_list = Market().listings()["data"]
TypeError: 'JSONDecodeError' object is not subscriptable
2021-05-06 17:09:04,488 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:09:04,489 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:09:09,807 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:09:09,808 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:09:10,878 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:09:10,878 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:09:14,326 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:09:14,327 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:09:18,894 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:09:18,895 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:09:24,024 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:09:24,025 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:09:29,342 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:09:29,343 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:09:37,013 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:09:37,024 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:09:41,093 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:09:41,094 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:09:52,551 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:09:52,551 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:09:56,628 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:09:56,629 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:10:16,984 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:10:16,985 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:10:42,683 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:10:42,683 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:10:46,760 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:10:46,760 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:11:25,275 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:11:25,275 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:11:29,344 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:11:29,345 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:11:59,415 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:11:59,416 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:12:03,487 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:12:03,488 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:12:33,554 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:12:33,554 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:12:37,628 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:12:37,629 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:13:07,696 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:13:07,696 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:13:11,777 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:13:11,779 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:13:24,187 - INFO - root - Plugin 'Update' added
2021-05-06 17:13:24,201 - INFO - root - Plugin 'Roi' added
2021-05-06 17:13:24,204 - INFO - root - Plugin 'Backup' added
2021-05-06 17:13:24,206 - INFO - root - Plugin 'Description' added
2021-05-06 17:13:24,209 - INFO - root - Plugin 'Alltimehigh' added
2021-05-06 17:13:24,211 - INFO - root - Plugin 'Social' added
2021-05-06 17:13:24,222 - INFO - root - Plugin 'Pools' added
2021-05-06 17:13:24,253 - INFO - root - Plugin 'Wallets' added
2021-05-06 17:13:24,254 - INFO - root - Plugin 'Feedback' added
2021-05-06 17:13:24,264 - INFO - root - Plugin 'Market' added
2021-05-06 17:13:24,267 - INFO - root - Plugin 'Events' added
2021-05-06 17:13:24,270 - INFO - root - Plugin 'Exchanges' added
2021-05-06 17:13:24,271 - INFO - root - Plugin 'Worst' added
2021-05-06 17:13:24,290 - INFO - root - Plugin 'Top' added
2021-05-06 17:13:24,293 - INFO - root - Plugin 'Shutdown' added
2021-05-06 17:13:24,300 - INFO - root - Plugin 'Manual' added
2021-05-06 17:13:24,306 - INFO - root - Plugin 'Repeat' added
2021-05-06 17:13:24,306 - INFO - root - Plugin 'Restart' added
2021-05-06 17:13:24,317 - INFO - root - Plugin 'Volume' added
2021-05-06 17:13:24,332 - INFO - root - Plugin 'Start' added
2021-05-06 17:13:24,333 - INFO - root - Plugin 'Developer' added
2021-05-06 17:13:24,334 - INFO - root - Plugin 'Change' added
2021-05-06 17:13:24,336 - INFO - root - Plugin 'Admin' added
2021-05-06 17:13:24,341 - INFO - root - Plugin 'Bpmn' added
2021-05-06 17:13:24,345 - WARNING - root - File 'alert.py' can't be loaded as a plugin: module 'opencryptobot.plugins.alert' has no attribute 'Alert'
2021-05-06 17:13:24,351 - INFO - root - Plugin 'Help' added
2021-05-06 17:13:24,356 - INFO - root - Plugin 'Info' added
2021-05-06 17:13:24,357 - INFO - root - Plugin 'About' added
2021-05-06 17:13:24,362 - INFO - root - Plugin 'People' added
2021-05-06 17:13:24,374 - INFO - root - Plugin 'Donate' added
2021-05-06 17:13:24,378 - INFO - root - Plugin 'Compare' added
2021-05-06 17:13:24,379 - INFO - root - Plugin 'Best' added
2021-05-06 17:13:24,384 - INFO - root - Plugin 'Stats' added
2021-05-06 17:13:24,402 - INFO - root - Plugin 'Search' added
2021-05-06 17:13:24,403 - INFO - root - Plugin 'Value' added
2021-05-06 17:13:24,415 - INFO - root - Plugin 'Fiftyone' added
2021-05-06 17:13:24,416 - INFO - root - Plugin 'News' added
2021-05-06 17:13:24,417 - INFO - root - Plugin 'Ico' added
2021-05-06 17:13:24,422 - INFO - root - Plugin 'Logfile' added
2021-05-06 17:13:24,423 - INFO - root - Plugin 'Team' added
2021-05-06 17:13:24,433 - INFO - root - Plugin 'Decentralized' added
2021-05-06 17:13:24,434 - INFO - root - Plugin 'Marketcap' added
2021-05-06 17:13:24,435 - INFO - root - Plugin 'Price' added
2021-05-06 17:13:24,674 - INFO - root - Plugin 'Whitepaper' added
2021-05-06 17:13:24,879 - INFO - root - Plugin 'Twitter' added
2021-05-06 17:13:27,937 - INFO - root - Plugin 'Global' added
2021-05-06 17:13:27,939 - INFO - root - Plugin 'Chart' added
2021-05-06 17:13:27,946 - INFO - root - Plugin 'Trends' added
2021-05-06 17:13:28,078 - INFO - root - Plugin 'Candlestick' added
2021-05-06 17:13:28,083 - INFO - root - Starting Caching
2021-05-06 17:13:29,450 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:13:29,451 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:13:31,475 - ERROR - JobQueue - An uncaught error was raised while executing job refresh
Traceback (most recent call last):
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 23, in refresh
    APICache.refresh_coinmarketcap_coin_list()
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 39, in refresh_coinmarketcap_coin_list
    APICache.cmc_coin_list = Market().listings()["data"]
TypeError: 'JSONDecodeError' object is not subscriptable
2021-05-06 17:13:33,526 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:13:33,526 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:13:34,596 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:13:34,597 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:13:39,166 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:13:39,166 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:13:40,738 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:13:44,817 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:13:44,819 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:13:44,852 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:13:46,417 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:13:46,418 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:13:47,084 - ERROR - root - Timed out - {'update_id': 406256767, 'message': {'message_id': 247, 'date': 1620310417, 'chat': {'id': 1062954233, 'type': 'private', 'username': 'paemmisyon', 'first_name': 'Paemisyon'}, 'text': '/p btc', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 2}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1062954233, 'first_name': 'Paemisyon', 'is_bot': False, 'username': 'paemmisyon', 'language_code': 'en'}}}
2021-05-06 17:13:48,270 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:13:48,270 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:13:50,138 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:13:50,138 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:13:52,456 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:13:52,457 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:13:55,901 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:13:55,901 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:13:59,343 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:13:59,343 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:14:04,478 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:04,479 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:14:09,672 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:09,675 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:14:16,486 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:16,486 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:14:20,335 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:20,336 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:14:24,157 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:24,158 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:14:35,616 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:35,619 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:14:37,177 - INFO - root - Plugin 'Backup' added
2021-05-06 17:14:37,194 - INFO - root - Plugin 'Manual' added
2021-05-06 17:14:37,195 - INFO - root - Plugin 'People' added
2021-05-06 17:14:37,218 - INFO - root - Plugin 'About' added
2021-05-06 17:14:37,225 - INFO - root - Plugin 'Alltimehigh' added
2021-05-06 17:14:37,230 - INFO - root - Plugin 'Social' added
2021-05-06 17:14:37,237 - INFO - root - Plugin 'Market' added
2021-05-06 17:14:37,246 - INFO - root - Plugin 'Stats' added
2021-05-06 17:14:37,254 - INFO - root - Plugin 'Value' added
2021-05-06 17:14:37,256 - INFO - root - Plugin 'Feedback' added
2021-05-06 17:14:37,260 - INFO - root - Plugin 'Team' added
2021-05-06 17:14:37,259 - INFO - root - Plugin 'Logfile' added
2021-05-06 17:14:37,274 - INFO - root - Plugin 'Admin' added
2021-05-06 17:14:37,277 - INFO - root - Plugin 'Change' added
2021-05-06 17:14:37,279 - INFO - root - Plugin 'Shutdown' added
2021-05-06 17:14:37,290 - INFO - root - Plugin 'Volume' added
2021-05-06 17:14:37,298 - INFO - root - Plugin 'Help' added
2021-05-06 17:14:37,298 - INFO - root - Plugin 'Top' added
2021-05-06 17:14:37,305 - INFO - root - Plugin 'Events' added
2021-05-06 17:14:37,309 - INFO - root - Plugin 'Search' added
2021-05-06 17:14:37,309 - INFO - root - Plugin 'Bpmn' added
2021-05-06 17:14:37,318 - INFO - root - Plugin 'Exchanges' added
2021-05-06 17:14:37,320 - INFO - root - Plugin 'Start' added
2021-05-06 17:14:37,320 - INFO - root - Plugin 'Ico' added
2021-05-06 17:14:37,322 - INFO - root - Plugin 'Repeat' added
2021-05-06 17:14:37,327 - INFO - root - Plugin 'Decentralized' added
2021-05-06 17:14:37,329 - INFO - root - Plugin 'Description' added
2021-05-06 17:14:37,329 - INFO - root - Plugin 'Update' added
2021-05-06 17:14:37,329 - INFO - root - Plugin 'Donate' added
2021-05-06 17:14:37,330 - INFO - root - Plugin 'Compare' added
2021-05-06 17:14:37,332 - INFO - root - Plugin 'Marketcap' added
2021-05-06 17:14:37,333 - INFO - root - Plugin 'Pools' added
2021-05-06 17:14:37,334 - INFO - root - Plugin 'Info' added
2021-05-06 17:14:37,334 - WARNING - root - File 'alert.py' can't be loaded as a plugin: module 'opencryptobot.plugins.alert' has no attribute 'Alert'
2021-05-06 17:14:37,335 - INFO - root - Plugin 'Best' added
2021-05-06 17:14:37,336 - INFO - root - Plugin 'Developer' added
2021-05-06 17:14:37,338 - INFO - root - Plugin 'Wallets' added
2021-05-06 17:14:37,338 - INFO - root - Plugin 'News' added
2021-05-06 17:14:37,345 - INFO - root - Plugin 'Roi' added
2021-05-06 17:14:37,346 - INFO - root - Plugin 'Restart' added
2021-05-06 17:14:37,348 - INFO - root - Plugin 'Worst' added
2021-05-06 17:14:37,349 - INFO - root - Plugin 'Price' added
2021-05-06 17:14:37,350 - INFO - root - Plugin 'Fiftyone' added
2021-05-06 17:14:37,540 - INFO - root - Plugin 'Whitepaper' added
2021-05-06 17:14:37,737 - INFO - root - Plugin 'Twitter' added
2021-05-06 17:14:39,688 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:39,688 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:14:40,300 - INFO - root - Plugin 'Global' added
2021-05-06 17:14:40,301 - INFO - root - Plugin 'Chart' added
2021-05-06 17:14:40,309 - INFO - root - Plugin 'Trends' added
2021-05-06 17:14:40,433 - INFO - root - Plugin 'Candlestick' added
2021-05-06 17:14:40,436 - INFO - root - Starting Caching
2021-05-06 17:14:41,821 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:41,822 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:14:44,701 - ERROR - JobQueue - An uncaught error was raised while executing job refresh
Traceback (most recent call last):
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 23, in refresh
    APICache.refresh_coinmarketcap_coin_list()
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 39, in refresh_coinmarketcap_coin_list
    APICache.cmc_coin_list = Market().listings()["data"]
TypeError: 'JSONDecodeError' object is not subscriptable
2021-05-06 17:14:46,398 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:46,400 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:14:47,466 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:47,467 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:14:52,790 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:52,790 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:14:53,410 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:53,410 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:14:54,368 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:58,436 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:58,437 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:14:59,861 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:59,870 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:14:59,870 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:15:00,759 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:00,759 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:15:01,495 - ERROR - root - Timed out - {'update_id': 406256768, 'message': {'message_id': 250, 'date': 1620310491, 'chat': {'id': 1062954233, 'type': 'private', 'username': 'paemmisyon', 'first_name': 'Paemisyon'}, 'text': '/p btc', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 2}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1062954233, 'first_name': 'Paemisyon', 'is_bot': False, 'username': 'paemmisyon', 'language_code': 'en'}}}
2021-05-06 17:15:04,439 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:04,440 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:15:05,918 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:10,889 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:10,889 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:15:11,235 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:11,235 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:15:16,368 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:19,812 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:19,813 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:15:21,553 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:21,554 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:15:25,718 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:29,222 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:29,223 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:15:33,850 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:33,850 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:15:34,270 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:41,934 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:41,935 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:15:45,315 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:45,316 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:15:46,003 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:49,888 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:49,889 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:15:57,463 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:15:57,463 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:01,547 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:16:02,546 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:02,546 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:02,547 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:02,547 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:02,547 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:02,547 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:02,551 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:02,551 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:07,045 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:16:07,046 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:10,753 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:16:10,754 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:11,620 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:16:11,621 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:18,772 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:16:18,773 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:36,456 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:16:36,456 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:40,525 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:16:40,526 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:41,697 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:16:41,697 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:46,265 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:16:46,266 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:47,472 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:16:47,472 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:16:49,791 - ERROR - telegram.ext.updater - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021-05-06 17:16:49,792 - ERROR - root - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409) - Class: TelegramBot - None
2021-05-06 17:17:09,528 - INFO - root - Plugin 'Backup' added
2021-05-06 17:17:09,532 - INFO - root - Plugin 'About' added
2021-05-06 17:17:09,533 - INFO - root - Plugin 'Worst' added
2021-05-06 17:17:09,536 - INFO - root - Plugin 'Marketcap' added
2021-05-06 17:17:09,545 - INFO - root - Plugin 'Help' added
2021-05-06 17:17:09,549 - INFO - root - Plugin 'Events' added
2021-05-06 17:17:09,551 - INFO - root - Plugin 'Change' added
2021-05-06 17:17:09,552 - INFO - root - Plugin 'Alltimehigh' added
2021-05-06 17:17:09,553 - INFO - root - Plugin 'Team' added
2021-05-06 17:17:09,560 - INFO - root - Plugin 'Ico' added
2021-05-06 17:17:09,564 - INFO - root - Plugin 'Description' added
2021-05-06 17:17:09,569 - INFO - root - Plugin 'Manual' added
2021-05-06 17:17:09,570 - INFO - root - Plugin 'Top' added
2021-05-06 17:17:09,572 - INFO - root - Plugin 'Admin' added
2021-05-06 17:17:09,581 - INFO - root - Plugin 'Logfile' added
2021-05-06 17:17:09,586 - INFO - root - Plugin 'Market' added
2021-05-06 17:17:09,589 - INFO - root - Plugin 'Restart' added
2021-05-06 17:17:09,596 - INFO - root - Plugin 'People' added
2021-05-06 17:17:09,603 - INFO - root - Plugin 'Wallets' added
2021-05-06 17:17:09,607 - INFO - root - Plugin 'Social' added
2021-05-06 17:17:09,608 - INFO - root - Plugin 'Exchanges' added
2021-05-06 17:17:09,611 - INFO - root - Plugin 'Search' added
2021-05-06 17:17:09,619 - INFO - root - Plugin 'Bpmn' added
2021-05-06 17:17:09,611 - INFO - root - Plugin 'Developer' added
2021-05-06 17:17:09,622 - INFO - root - Plugin 'Repeat' added
2021-05-06 17:17:09,624 - INFO - root - Plugin 'Value' added
2021-05-06 17:17:09,625 - INFO - root - Plugin 'Volume' added
2021-05-06 17:17:09,632 - INFO - root - Plugin 'Update' added
2021-05-06 17:17:09,632 - INFO - root - Plugin 'Decentralized' added
2021-05-06 17:17:09,642 - INFO - root - Plugin 'Start' added
2021-05-06 17:17:09,643 - INFO - root - Plugin 'Pools' added
2021-05-06 17:17:09,645 - INFO - root - Plugin 'Shutdown' added
2021-05-06 17:17:09,654 - INFO - root - Plugin 'Feedback' added
2021-05-06 17:17:09,655 - INFO - root - Plugin 'Stats' added
2021-05-06 17:17:09,657 - INFO - root - Plugin 'Best' added
2021-05-06 17:17:09,662 - INFO - root - Plugin 'Donate' added
2021-05-06 17:17:09,664 - INFO - root - Plugin 'Compare' added
2021-05-06 17:17:09,671 - WARNING - root - File 'alert.py' can't be loaded as a plugin: module 'opencryptobot.plugins.alert' has no attribute 'Alert'
2021-05-06 17:17:09,673 - INFO - root - Plugin 'Fiftyone' added
2021-05-06 17:17:09,674 - INFO - root - Plugin 'Roi' added
2021-05-06 17:17:09,677 - INFO - root - Plugin 'News' added
2021-05-06 17:17:09,693 - INFO - root - Plugin 'Info' added
2021-05-06 17:17:09,696 - INFO - root - Plugin 'Price' added
2021-05-06 17:17:09,918 - INFO - root - Plugin 'Whitepaper' added
2021-05-06 17:17:10,032 - INFO - root - Plugin 'Twitter' added
2021-05-06 17:17:10,871 - INFO - root - Plugin 'Global' added
2021-05-06 17:17:10,873 - INFO - root - Plugin 'Chart' added
2021-05-06 17:17:10,875 - INFO - root - Plugin 'Trends' added
2021-05-06 17:17:10,915 - INFO - root - Plugin 'Candlestick' added
2021-05-06 17:17:10,919 - INFO - root - Starting Caching
2021-05-06 17:17:22,475 - ERROR - JobQueue - An uncaught error was raised while executing job refresh
Traceback (most recent call last):
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 23, in refresh
    APICache.refresh_coinmarketcap_coin_list()
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 39, in refresh_coinmarketcap_coin_list
    APICache.cmc_coin_list = Market().listings()["data"]
TypeError: 'JSONDecodeError' object is not subscriptable
2021-05-06 17:17:59,326 - ERROR - telegram.ext.dispatcher - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/plugin.py", line 106, in _save_data
    return func(self, bot, update, **kwargs)
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/plugin.py", line 73, in _send_typing_action
    return func(self, bot, update, **kwargs)
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/plugins/price.py", line 141, in get_action
    msg += f"\n[Hemen {base_coin} Buy]({self.CG_URL}{coin_symbol})"
UnboundLocalError: local variable 'base_coin' referenced before assignment
2021-05-06 17:23:27,664 - INFO - root - Plugin 'Update' added
2021-05-06 17:23:27,680 - INFO - root - Plugin 'Feedback' added
2021-05-06 17:23:27,686 - INFO - root - Plugin 'Logfile' added
2021-05-06 17:23:27,686 - INFO - root - Plugin 'Market' added
2021-05-06 17:23:27,696 - INFO - root - Plugin 'Top' added
2021-05-06 17:23:27,698 - INFO - root - Plugin 'Exchanges' added
2021-05-06 17:23:27,702 - INFO - root - Plugin 'Team' added
2021-05-06 17:23:27,704 - INFO - root - Plugin 'About' added
2021-05-06 17:23:27,707 - INFO - root - Plugin 'Restart' added
2021-05-06 17:23:27,707 - INFO - root - Plugin 'Wallets' added
2021-05-06 17:23:27,709 - INFO - root - Plugin 'Stats' added
2021-05-06 17:23:27,727 - INFO - root - Plugin 'Start' added
2021-05-06 17:23:27,732 - INFO - root - Plugin 'Help' added
2021-05-06 17:23:27,734 - INFO - root - Plugin 'Description' added
2021-05-06 17:23:27,735 - INFO - root - Plugin 'Manual' added
2021-05-06 17:23:27,738 - INFO - root - Plugin 'Change' added
2021-05-06 17:23:27,738 - WARNING - root - File 'alert.py' can't be loaded as a plugin: module 'opencryptobot.plugins.alert' has no attribute 'Alert'
2021-05-06 17:23:27,738 - INFO - root - Plugin 'Volume' added
2021-05-06 17:23:27,743 - INFO - root - Plugin 'Admin' added
2021-05-06 17:23:27,744 - INFO - root - Plugin 'People' added
2021-05-06 17:23:27,749 - INFO - root - Plugin 'Value' added
2021-05-06 17:23:27,752 - INFO - root - Plugin 'Marketcap' added
2021-05-06 17:23:27,756 - INFO - root - Plugin 'Bpmn' added
2021-05-06 17:23:27,768 - INFO - root - Plugin 'Worst' added
2021-05-06 17:23:27,772 - INFO - root - Plugin 'Backup' added
2021-05-06 17:23:27,775 - INFO - root - Plugin 'Compare' added
2021-05-06 17:23:27,776 - INFO - root - Plugin 'Pools' added
2021-05-06 17:23:27,777 - INFO - root - Plugin 'Developer' added
2021-05-06 17:23:27,787 - INFO - root - Plugin 'Shutdown' added
2021-05-06 17:23:27,790 - INFO - root - Plugin 'Info' added
2021-05-06 17:23:27,791 - INFO - root - Plugin 'Social' added
2021-05-06 17:23:27,794 - INFO - root - Plugin 'Alltimehigh' added
2021-05-06 17:23:27,794 - INFO - root - Plugin 'Roi' added
2021-05-06 17:23:27,802 - INFO - root - Plugin 'Decentralized' added
2021-05-06 17:23:27,803 - INFO - root - Plugin 'Search' added
2021-05-06 17:23:27,804 - INFO - root - Plugin 'Repeat' added
2021-05-06 17:23:27,804 - INFO - root - Plugin 'Events' added
2021-05-06 17:23:27,805 - INFO - root - Plugin 'Ico' added
2021-05-06 17:23:27,805 - INFO - root - Plugin 'Donate' added
2021-05-06 17:23:27,807 - INFO - root - Plugin 'Best' added
2021-05-06 17:23:27,813 - INFO - root - Plugin 'Fiftyone' added
2021-05-06 17:23:27,814 - INFO - root - Plugin 'News' added
2021-05-06 17:23:27,823 - INFO - root - Plugin 'Price' added
2021-05-06 17:23:28,039 - INFO - root - Plugin 'Whitepaper' added
2021-05-06 17:23:28,209 - INFO - root - Plugin 'Twitter' added
2021-05-06 17:23:31,042 - INFO - root - Plugin 'Global' added
2021-05-06 17:23:31,044 - INFO - root - Plugin 'Chart' added
2021-05-06 17:23:31,055 - INFO - root - Plugin 'Trends' added
2021-05-06 17:23:31,177 - INFO - root - Plugin 'Candlestick' added
2021-05-06 17:23:31,182 - INFO - root - Starting Caching
2021-05-06 17:23:33,638 - ERROR - JobQueue - An uncaught error was raised while executing job refresh
Traceback (most recent call last):
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 23, in refresh
    APICache.refresh_coinmarketcap_coin_list()
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 39, in refresh_coinmarketcap_coin_list
    APICache.cmc_coin_list = Market().listings()["data"]
TypeError: 'JSONDecodeError' object is not subscriptable
2021-05-06 17:25:31,136 - INFO - root - Plugin 'Feedback' added
2021-05-06 17:25:31,144 - INFO - root - Plugin 'Exchanges' added
2021-05-06 17:25:31,146 - INFO - root - Plugin 'Shutdown' added
2021-05-06 17:25:31,148 - INFO - root - Plugin 'Backup' added
2021-05-06 17:25:31,154 - INFO - root - Plugin 'Ico' added
2021-05-06 17:25:31,165 - INFO - root - Plugin 'People' added
2021-05-06 17:25:31,167 - INFO - root - Plugin 'Wallets' added
2021-05-06 17:25:31,172 - INFO - root - Plugin 'Events' added
2021-05-06 17:25:31,174 - INFO - root - Plugin 'Pools' added
2021-05-06 17:25:31,174 - INFO - root - Plugin 'Start' added
2021-05-06 17:25:31,194 - INFO - root - Plugin 'Volume' added
2021-05-06 17:25:31,198 - INFO - root - Plugin 'Donate' added
2021-05-06 17:25:31,198 - INFO - root - Plugin 'Repeat' added
2021-05-06 17:25:31,213 - INFO - root - Plugin 'Update' added
2021-05-06 17:25:31,233 - INFO - root - Plugin 'Bpmn' added
2021-05-06 17:25:31,236 - INFO - root - Plugin 'Developer' added
2021-05-06 17:25:31,239 - INFO - root - Plugin 'Top' added
2021-05-06 17:25:31,255 - INFO - root - Plugin 'About' added
2021-05-06 17:25:31,259 - INFO - root - Plugin 'Description' added
2021-05-06 17:25:31,269 - INFO - root - Plugin 'Help' added
2021-05-06 17:25:31,270 - INFO - root - Plugin 'Compare' added
2021-05-06 17:25:31,275 - INFO - root - Plugin 'Social' added
2021-05-06 17:25:31,275 - INFO - root - Plugin 'Change' added
2021-05-06 17:25:31,277 - INFO - root - Plugin 'Search' added
2021-05-06 17:25:31,277 - INFO - root - Plugin 'Value' added
2021-05-06 17:25:31,278 - WARNING - root - File 'alert.py' can't be loaded as a plugin: module 'opencryptobot.plugins.alert' has no attribute 'Alert'
2021-05-06 17:25:31,280 - INFO - root - Plugin 'Stats' added
2021-05-06 17:25:31,282 - INFO - root - Plugin 'Worst' added
2021-05-06 17:25:31,283 - INFO - root - Plugin 'Admin' added
2021-05-06 17:25:31,289 - INFO - root - Plugin 'Roi' added
2021-05-06 17:25:31,292 - INFO - root - Plugin 'Logfile' added
2021-05-06 17:25:31,297 - INFO - root - Plugin 'Alltimehigh' added
2021-05-06 17:25:31,301 - INFO - root - Plugin 'Team' added
2021-05-06 17:25:31,305 - INFO - root - Plugin 'Restart' added
2021-05-06 17:25:31,305 - INFO - root - Plugin 'Manual' added
2021-05-06 17:25:31,312 - INFO - root - Plugin 'Fiftyone' added
2021-05-06 17:25:31,312 - INFO - root - Plugin 'Best' added
2021-05-06 17:25:31,313 - INFO - root - Plugin 'News' added
2021-05-06 17:25:31,315 - INFO - root - Plugin 'Decentralized' added
2021-05-06 17:25:31,315 - INFO - root - Plugin 'Info' added
2021-05-06 17:25:31,318 - INFO - root - Plugin 'Marketcap' added
2021-05-06 17:25:31,333 - INFO - root - Plugin 'Market' added
2021-05-06 17:25:31,353 - INFO - root - Plugin 'Price' added
2021-05-06 17:25:31,505 - INFO - root - Plugin 'Whitepaper' added
2021-05-06 17:25:31,621 - INFO - root - Plugin 'Twitter' added
2021-05-06 17:25:32,371 - INFO - root - Plugin 'Global' added
2021-05-06 17:25:32,372 - INFO - root - Plugin 'Chart' added
2021-05-06 17:25:32,375 - INFO - root - Plugin 'Trends' added
2021-05-06 17:25:32,428 - INFO - root - Plugin 'Candlestick' added
2021-05-06 17:25:32,431 - INFO - root - Starting Caching
2021-05-06 17:25:35,187 - ERROR - JobQueue - An uncaught error was raised while executing job refresh
Traceback (most recent call last):
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 23, in refresh
    APICache.refresh_coinmarketcap_coin_list()
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 39, in refresh_coinmarketcap_coin_list
    APICache.cmc_coin_list = Market().listings()["data"]
TypeError: 'JSONDecodeError' object is not subscriptable
2021-05-06 17:30:07,957 - INFO - root - Plugin 'Backup' added
2021-05-06 17:30:07,974 - INFO - root - Plugin 'Feedback' added
2021-05-06 17:30:07,990 - INFO - root - Plugin 'Events' added
2021-05-06 17:30:07,997 - INFO - root - Plugin 'Top' added
2021-05-06 17:30:08,002 - INFO - root - Plugin 'Stats' added
2021-05-06 17:30:08,017 - INFO - root - Plugin 'Update' added
2021-05-06 17:30:08,019 - INFO - root - Plugin 'Alltimehigh' added
2021-05-06 17:30:08,030 - INFO - root - Plugin 'Compare' added
2021-05-06 17:30:08,036 - INFO - root - Plugin 'Repeat' added
2021-05-06 17:30:08,036 - INFO - root - Plugin 'Team' added
2021-05-06 17:30:08,044 - INFO - root - Plugin 'Search' added
2021-05-06 17:30:08,044 - INFO - root - Plugin 'Roi' added
2021-05-06 17:30:08,050 - INFO - root - Plugin 'Worst' added
2021-05-06 17:30:08,053 - WARNING - root - File 'alert.py' can't be loaded as a plugin: module 'opencryptobot.plugins.alert' has no attribute 'Alert'
2021-05-06 17:30:08,054 - INFO - root - Plugin 'Value' added
2021-05-06 17:30:08,058 - INFO - root - Plugin 'Manual' added
2021-05-06 17:30:08,060 - INFO - root - Plugin 'Volume' added
2021-05-06 17:30:08,062 - INFO - root - Plugin 'About' added
2021-05-06 17:30:08,065 - INFO - root - Plugin 'People' added
2021-05-06 17:30:08,065 - INFO - root - Plugin 'Shutdown' added
2021-05-06 17:30:08,074 - INFO - root - Plugin 'Developer' added
2021-05-06 17:30:08,075 - INFO - root - Plugin 'Best' added
2021-05-06 17:30:08,085 - INFO - root - Plugin 'Social' added
2021-05-06 17:30:08,087 - INFO - root - Plugin 'Logfile' added
2021-05-06 17:30:08,089 - INFO - root - Plugin 'Bpmn' added
2021-05-06 17:30:08,090 - INFO - root - Plugin 'Help' added
2021-05-06 17:30:08,092 - INFO - root - Plugin 'Ico' added
2021-05-06 17:30:08,093 - INFO - root - Plugin 'Start' added
2021-05-06 17:30:08,099 - INFO - root - Plugin 'Admin' added
2021-05-06 17:30:08,100 - INFO - root - Plugin 'Description' added
2021-05-06 17:30:08,104 - INFO - root - Plugin 'Exchanges' added
2021-05-06 17:30:08,106 - INFO - root - Plugin 'Marketcap' added
2021-05-06 17:30:08,113 - INFO - root - Plugin 'Decentralized' added
2021-05-06 17:30:08,114 - INFO - root - Plugin 'Wallets' added
2021-05-06 17:30:08,115 - INFO - root - Plugin 'Market' added
2021-05-06 17:30:08,115 - INFO - root - Plugin 'Info' added
2021-05-06 17:30:08,117 - INFO - root - Plugin 'Pools' added
2021-05-06 17:30:08,124 - INFO - root - Plugin 'Change' added
2021-05-06 17:30:08,124 - INFO - root - Plugin 'Price' added
2021-05-06 17:30:08,128 - INFO - root - Plugin 'Donate' added
2021-05-06 17:30:08,128 - INFO - root - Plugin 'Fiftyone' added
2021-05-06 17:30:08,129 - INFO - root - Plugin 'Restart' added
2021-05-06 17:30:08,132 - INFO - root - Plugin 'News' added
2021-05-06 17:30:08,311 - INFO - root - Plugin 'Whitepaper' added
2021-05-06 17:30:08,432 - INFO - root - Plugin 'Twitter' added
2021-05-06 17:30:09,484 - INFO - root - Plugin 'Global' added
2021-05-06 17:30:09,485 - INFO - root - Plugin 'Chart' added
2021-05-06 17:30:09,489 - INFO - root - Plugin 'Trends' added
2021-05-06 17:30:09,532 - INFO - root - Plugin 'Candlestick' added
2021-05-06 17:30:09,536 - INFO - root - Starting Caching
2021-05-06 17:30:15,763 - ERROR - JobQueue - An uncaught error was raised while executing job refresh
Traceback (most recent call last):
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "/Users/ahmetcnd/.local/share/virtualenvs/openCryptoBot-D8P4_yx3/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 23, in refresh
    APICache.refresh_coinmarketcap_coin_list()
  File "/Users/ahmetcnd/Documents/telegrambot/openCryptoBot/opencryptobot/api/apicache.py", line 39, in refresh_coinmarketcap_coin_list
    APICache.cmc_coin_list = Market().listings()["data"]
TypeError: 'JSONDecodeError' object is not subscriptable
2021-05-06 18:00:03,362 - ERROR - root - Timed out - {'update_id': 406256773, 'message': {'message_id': 263, 'date': 1620313193, 'chat': {'id': 1062954233, 'type': 'private', 'username': 'paemmisyon', 'first_name': 'Paemisyon'}, 'text': '/cs btt', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 3}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1062954233, 'first_name': 'Paemisyon', 'is_bot': False, 'username': 'paemmisyon', 'language_code': 'tr'}}}
